CC = gcc
CPP = g++

CURDIR = $(shell pwd)
SRCDIR = $(CURDIR)/../src

WARNINGS = -Wall -Wstrict-prototypes -fwrapv
DEBUG = -g -ggdb
LIBRARY = -lpthread
INCLUDE = -I $(LOGDIR)

.PHONY : clean

clean :


